Repository code-rhapsodie/dataflow-bundle, pull requests merged in 2019-11, with the labels that each got.

#10 change branch alias to start v2 dev
  composer.json
Labels: enhancement

#17 remove ORM and rewrite repository
  Tests/Manager/ScheduledDataflowManagerTest.php
  Tests/Runner/PendingDataflowRunnerTest.php
  src/Command/AddScheduledDataflowCommand.php
  src/Command/ChangeScheduleStatusCommand.php
  src/Command/ScheduleListCommand.php
  src/DataflowType/Dataflow/Dataflow.php
  src/Entity/Job.php
  src/Entity/ScheduledDataflow.php
  src/Manager/ScheduledDataflowManager.php
  src/Registry/DataflowTypeRegistry.php
  src/Repository/InitFromDbTrait.php
  src/Repository/JobRepository.php
  src/Repository/ScheduledDataflowRepository.php
  src/Resources/config/services.yaml
  src/Runner/PendingDataflowRunner.php
Labels: enhancement

#20 add factory to determine the current connexion #14
  src/Factory/ConnectionFactory.php
  src/Resources/config/services.yaml
Labels: enhancement

#22 add connection option for all command #15
  src/Command/AddScheduledDataflowCommand.php
  src/Command/ChangeScheduleStatusCommand.php
  src/Command/ExecuteDataflowCommand.php
  src/Command/JobShowCommand.php
  src/Command/RunPendingDataflowsCommand.php
  src/Command/ScheduleListCommand.php
  src/Factory/ConnectionFactory.php
Labels: enhancement

#23 Add schema provider
  src/Command/AddScheduledDataflowCommand.php
  src/Command/ChangeScheduleStatusCommand.php
  src/Command/ExecuteDataflowCommand.php
  src/Command/JobShowCommand.php
  src/Command/RunPendingDataflowsCommand.php
  src/Command/ScheduleListCommand.php
  src/Command/SchemaCommand.php
  src/Resources/config/services.yaml
  src/SchemaProvider/DataflowSchemaProvider.php
Labels: enhancement

#25 refactor getQueryBuilder and change visibility
  src/Repository/JobRepository.php
  src/Repository/ScheduledDataflowRepository.php
Labels: enhancement

#24 add docs for v2 #21
  CHANGELOG.md
  README.md
  UPGRADE.md
Labels: documentation, enhancement

#26 fix json_decode on null
  src/Repository/InitFromDbTrait.php
Labels: bug

#27 fix command dependency injection
  src/Repository/InitFromDbTrait.php
  src/Resources/config/services.yaml
Labels: bug

#28 make coderhapsodie.dataflow.connection as alias
  src/Resources/config/services.yaml
Labels: enhancement

#29 add depentency to doctrine/doctrine-bundle
  composer.json
Labels: bug

#30 replace dependency to doctrine/orm by doctrine/dbal
  composer.json
Labels: bug

#34 Added CollectionWriter and DelegatorWriter
  CHANGELOG.md
  README.md
  Tests/DataflowType/AbstractDataflowTypeTest.php
  Tests/DataflowType/Writer/CollectionWriterTest.php
  Tests/DataflowType/Writer/DelegatorWriterTest.php
  src/DataflowType/Writer/CollectionWriter.php
  src/DataflowType/Writer/DelegateWriterInterface.php
  src/DataflowType/Writer/DelegatorWriter.php
  src/DataflowType/Writer/WriterInterface.php
  src/Exceptions/UnsupportedItemTypeException.php
Labels: enhancement

#36 Fixed next execution for scheduled dataflows not increasing
  Tests/Manager/ScheduledDataflowManagerTest.php
  src/Manager/ScheduledDataflowManager.php
Labels: bug

#35 Add Symfony 5.0 compatibility
  .travis.yml
  CHANGELOG.md
  Tests/Manager/ScheduledDataflowManagerTest.php
  Tests/Runner/PendingDataflowRunnerTest.php
  composer.json
  src/Event/CrEvent.php
  src/Event/ProcessingEvent.php
  src/Runner/PendingDataflowRunner.php
Labels: enhancement

#38 Removed unused dependency
  composer.json
Labels: enhancement
